name: RSSI Averaging
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: mqtt-raw
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: rssi-average
    required: true
  - name: ma_window_size
    inputType: FreeText
    description: hopping window size
    defaultValue: 2000
    required: true
  - name: ma_step
    inputType: FreeText
    description: hopping window step
    defaultValue: 500
    required: true
  - name: ma_grace
    inputType: FreeText
    description: hopping window grace
    defaultValue: 100
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
